import { ClientRequestItem } from '../types/clientRequests';

const CLIENT_REQUET: ClientRequestItem[] = [
  {
    id: 'req_101',
    name: 'John Smith',
    avatarUrl: 'https://randomuser.me/api/portraits/men/1.jpg',
    isVerified: true,
    intent: 'Buy',
    distance: '50 mi away',
    address: '123 Main St, Apt 4B',
    selectedSlot: '2026-12-11 at 3:00 PM',
    clientNotes: 'Prefer to move within 2 months. Have pre-approval from bank.',
    status: 'pending',
  },
  {
    id: 'req_102',
    name: 'William Butcher',
    avatarUrl: 'https://randomuser.me/api/portraits/men/15.jpg',
    isVerified: false,
    intent: 'Rent',
    distance: '150 mi away',
    address: '154 North St, Apt 5C',
    selectedSlot: '2026-12-14 at 11:00 AM',
    clientNotes: 'Looking for a furnished apartment near downtown.',
    status: 'pending',
  },
  {
    id: 'req_103',
    name: 'Maria Johnson',
    avatarUrl: 'https://randomuser.me/api/portraits/women/21.jpg',
    isVerified: true,
    intent: 'Sell',
    distance: '80 mi away',
    address: '54 South St, Apt 3A',
    selectedSlot: '2026-12-10 at 4:30 PM',
    clientNotes: 'Need to sell property before relocating.',
    status: 'approved',
    budgetRange: '$500,000 - $650,000',
    propertyType: 'Apartment',
    configuration: '2 BHK',
    preferredArea: 'Jakarta, Indonesia',
    isReviewRequested: false,
  },
  {
    id: 'req_104',
    name: 'Sophia Brown',
    avatarUrl: 'https://randomuser.me/api/portraits/women/45.jpg',
    isVerified: true,
    intent: 'Buy',
    distance: '25 mi away',
    address: '890 Park Avenue',
    selectedSlot: '2026-12-16 at 10:00 AM',
    clientNotes: 'Interested in newly constructed villas.',
    status: 'pending',
  },
  {
    id: 'req_105',
    name: 'David Wilson',
    avatarUrl: 'https://randomuser.me/api/portraits/men/35.jpg',
    isVerified: false,
    intent: 'Rent',
    distance: '10 mi away',
    address: '67 Lake View Road',
    selectedSlot: '2026-12-18 at 2:30 PM',
    clientNotes: 'Need a pet-friendly apartment.',
    status: 'pending',
  },
  {
    id: 'req_106',
    name: 'Emma Davis',
    avatarUrl: 'https://randomuser.me/api/portraits/women/12.jpg',
    isVerified: true,
    intent: 'Buy',
    distance: '45 mi away',
    address: '18 Sunset Boulevard',
    selectedSlot: '2026-12-20 at 12:00 PM',
    clientNotes: 'Budget is flexible for a premium location.',
    status: 'approved',
    budgetRange: '$700,000 - $900,000',
    propertyType: 'Villa',
    configuration: '4 BHK',
    preferredArea: 'Bali, Indonesia',
    isReviewRequested: true,
  },
  {
    id: 'req_107',
    name: 'James Anderson',
    avatarUrl: 'https://randomuser.me/api/portraits/men/52.jpg',
    isVerified: true,
    intent: 'Sell',
    distance: '90 mi away',
    address: '432 Oak Street',
    selectedSlot: '2026-12-21 at 5:00 PM',
    clientNotes: 'Property is available immediately.',
    status: 'approved',
    budgetRange: '$350,000 - $450,000',
    propertyType: 'House',
    configuration: '3 BHK',
    preferredArea: 'Bandung, Indonesia',
    isReviewRequested: false,
  },
  {
    id: 'req_108',
    name: 'Olivia Taylor',
    avatarUrl: 'https://randomuser.me/api/portraits/women/65.jpg',
    isVerified: false,
    intent: 'Rent',
    distance: '18 mi away',
    address: '91 River Side',
    selectedSlot: '2026-12-22 at 9:30 AM',
    clientNotes: 'Looking for a studio apartment.',
    status: 'pending',
  },
  {
    id: 'req_109',
    name: 'Michael Thomas',
    avatarUrl: 'https://randomuser.me/api/portraits/men/74.jpg',
    isVerified: true,
    intent: 'Buy',
    distance: '35 mi away',
    address: '220 Green Park',
    selectedSlot: '2026-12-23 at 4:00 PM',
    clientNotes: 'Need a family home with parking.',
    status: 'approved',
    budgetRange: '$450,000 - $550,000',
    propertyType: 'Townhouse',
    configuration: '3 BHK',
    preferredArea: 'Surabaya, Indonesia',
    isReviewRequested: true,
  },
  {
    id: 'req_110',
    name: 'Isabella Martinez',
    avatarUrl: 'https://randomuser.me/api/portraits/women/88.jpg',
    isVerified: true,
    intent: 'Sell',
    distance: '70 mi away',
    address: '501 Palm Street',
    selectedSlot: '2026-12-24 at 1:00 PM',
    clientNotes: 'Recently renovated property.',
    status: 'approved',
    budgetRange: '$800,000 - $950,000',
    propertyType: 'Villa',
    configuration: '5 BHK',
    preferredArea: 'Jakarta, Indonesia',
    isReviewRequested: false,
  },
];

export const clientRequestService = {
  getAllRequests: async (): Promise<ClientRequestItem[]> => {
    return new Promise(resolve => {
      setTimeout(() => {
        resolve(CLIENT_REQUET);
      }, 500);
    });
  },

  acceptRequest: async (requestId: string): Promise<boolean> => {
    return true;
  },

  cancleRequest: async (requestId: string): Promise<boolean> => {
    return false;
  },

  sendReviewRequest: async (requestId: string): Promise<boolean> => {
    return true;
  },
};
